sudo: required
dist: trusty

language: python
python:
  - "3.5"

before_install:
  - sudo apt-get install -y liblas-c3 libopenblas-base

install:
  - pip install -e .
  - pip install pytest pytest-benchmark

script:
  - pytest
  - py3dtiles info tests/pointCloudRGB.pnts

addons:
  apt:
    update: true
