sudo: required
dist: bionic

language: python
python:
  - "3.6"

before_install:
  - sudo add-apt-repository universe
  - sudo apt-get install -y liblas-c3 libopenblas-base flake8

install:
  - pip install -e .
  - pip install -e .[dev]

script:
  - pytest
  - flake8 setup.py py3dtiles/
  - py3dtiles info tests/pointCloudRGB.pnts

addons:
  apt:
    update: true
